_target_: bayesflow.networks.FlowMatching
subnet: mlp
subnet_kwargs:
  _target_: builtins.dict
  widths:
    _target_: sweeper.constant_list
    length: ${mlp_depth}
    value:
      _target_: builtins.pow
      base: 2
      exp: ${mlp_width}
  dropout: ${mlp_dropout}
  activation: mish
  kernel_initializer: he_normal
  residual: ${mlp_residual}
  spectral_normalization: ${mlp_spectral_normalization}
base_distribution: ${base_distribution}
loss_fn: mse
use_optimal_transport: ${use_optimal_transport}
optimal_transport_kwargs: null
integrate_kwargs:
  _target_: builtins.dict
  method: euler
  steps: 100
