_target_: bayesflow.simulators.LambdaSimulator
sample_fn:
  _target_: confrdm.simulators.rdmc.sample_rdmc_prior_single_accumulator
  _partial_: true
  drift_c_loc: 0.5
  drift_c_scale: 0.1
  amp_shape: 10
  amp_scale: 2
  tau_shape: 8
  tau_scale: 10
  sd_shape: 80
  sd_scale: 0.05
  threshold_shape: 100
  threshold_scale: 0.7
  t0_loc: 300
  t0_scale: 200
  rng:
    _target_: numpy.random.default_rng
    seed: ${seed}