_target_: bayesflow.simulators.LambdaSimulator
sample_fn:
  _target_: confrdm.simulators.rdmc.sample_rdmc_prior_single_accumulator
  _partial_: true
  drift_c_loc: 4.0
  drift_c_scale: 0.5
  amp_loc: 0.1
  amp_scale: 0.05
  tau_loc: 0.1
  tau_scale: 0.05
  sd_loc: 0.9
  sd_scale: 0.1
  threshold_shape: 8.0
  threshold_scale: 0.1
  t0_loc: 0.3
  t0_scale: 0.05
  rng:
    _target_: numpy.random.default_rng
    seed: ${seed}