defaults:
  - /prior@training_prior: crdm_single_uniform
  - /prior@recovery_prior: crdm_informed

sampler:
  _target_: confrdm_jax.simulators.sample_conditional_crdm_single
  dt: 0.004
  t_max: 4.0

test_sampler:
  _target_: confrdm_jax.simulators.sample_conditional_crdm_condition
  _partial_: true
  dt: 0.001
  t_max: 4.0

log_prior:
  _target_: confrdm_jax.priors.crdm_prior
  _partial_: true

likelihood_factory_approx:
  _target_: confrdm_jax.likelihoods.create_crdm_likelihood_factory_approx
  _partial_: true

run_reference_recovery: false

num_bins: 4
num_mid: 64
num_params: 5

hierarchical:
  num_params: 7
  param_names: ["v_c_intercept", "v_c_slope", "amp", "tau", "s_true", "b", "t0"]
  prior_factory:
    _target_: confrdm_jax.simulators.create_hierarchical_crdm_prior_lkj_mvn
    _partial_: true
  test_sampler:
    _target_: confrdm_jax.simulators.sample_conditional_crdm_hierarchical_lkj_mvn
    _partial_: true
    dt: 0.001
    t_max: 4.0
  likelihood_factory_approx:
    _target_: confrdm_jax.likelihoods.create_crdm_hierarchical_likelihood_factory_approx
    _partial_: true
  prior:
    lkj_concentration: 2.0
    inverse_gamma_scale:    [0.4, 0.8, 0.4, 0.4, 0.8, 0.8, 0.25]
    mu_loc:                 [0.1, 0.5, -1.4, -2.2, -0.2, -0.2, -1.2]
    mu_scale:               [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.1]
