defaults:
  - /prior@training_prior: wald_uniform
  - /prior@recovery_prior: rdm_informed

sampler:
  _target_: confrdm_jax.simulators.sample_conditional_wald

test_sampler:
  _target_: confrdm_jax.simulators.sample_conditional_rdm
  _partial_: true

likelihood_factory_approx:
  _target_: confrdm_jax.likelihoods.create_rdm_likelihood_factory_approx
  _partial_: true

likelihood_factory_ref:
  _target_: confrdm_jax.likelihoods.create_rdm_two_accumulators_likelihood
  _partial_: true

run_reference_recovery: true

num_bins: 4
num_mid: 64
num_params: 3

hierarchical:
  num_params: 5
  param_names: ["v_intercept", "v_slope", "s_true", "b", "t0"]
  prior_factory:
    _target_: confrdm_jax.simulators.create_hierarchical_rdm_prior_lkj_mvn
    _partial_: true
  test_sampler:
    _target_: confrdm_jax.simulators.sample_conditional_rdm_hierarchical_lkj_mvn
    _partial_: true
  likelihood_factory_approx:
    _target_: confrdm_jax.likelihoods.create_rdm_hierarchical_likelihood_factory_approx
    _partial_: true
  likelihood_factory_ref:
    _target_: confrdm_jax.likelihoods.create_rdm_hierarchical_likelihood
    _partial_: true
  prior:
    lkj_concentration: 2.0
    inverse_gamma_scale:    [0.4, 0.4, 0.4, 0.4, 0.25]
    mu_loc:                 [0.1, 0.3, 0.4, 0.4, -1.2]
    mu_scale:               [0.25, 0.25, 0.25, 0.25, 0.1]
